In [31]:
import numpy as np
import requests
import pandas as pd
from tensorflow.keras.models import load_model
from array import array

In [32]:
model = load_model("neural_network.h5")

In [33]:
x = requests.get('http://127.0.0.1:5000/api/v1.0/stars')
lastInput = x.json()[-1]

In [34]:
y = pd.DataFrame.from_dict(lastInput, orient='index').values

In [35]:
y2 = np.squeeze(pd.DataFrame.from_dict(lastInput, orient='index').values)

In [36]:
y

array([[4.],
       [0.],
       [4.],
       [4.],
       [5.],
       [4.]])

In [43]:
y2.shape

(6,)

In [47]:
encoded_predictions = model.predict_classes(np.array([[0.1, 0.1, 0.1, 0.1, 0.1, 0.1]]))
#prediction_labels = label_encoder.inverse_transform(encoded_predictions)
encoded_predictions

array([1], dtype=int64)

In [56]:
encoded_predictions = model.predict_classes(np.array([list(lastInput.values())]))
#prediction_labels = label_encoder.inverse_transform(encoded_predictions)
encoded_predictions

array([1], dtype=int64)